export const FIREBASE_CONFIG = {
    apiKey: "AIzaSyDxEV7W2m4jbJiVl0Sc6cN7gBH7oWu_rl8",
    authDomain: "binyanshalem-28b1a.firebaseapp.com",
    projectId: "binyanshalem-28b1a",
    storageBucket: "binyanshalem-28b1a.firebasestorage.app",
    messagingSenderId: "923017150407",
    appId: "1:923017150407:web:35d71ffa41943bbbf623e2",
    measurementId: "G-YRWCMR3HVD"
};

export const BAKED_IN_RESOURCES = [
    {
        id: "anshei-shalom-shiur",
        type: "video",
        title: "Shalom Bayit Shiur in Anshei Shalom",
        speaker: "R' Bentzion Shafier",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v287610",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/287610/287610.jpg",
        imageAlt: "R' Bentzion Shafier presenting the Shalom Bayit shiur",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9287610"
    },
    {
        id: "korach-shalom-bayit",
        type: "video",
        title: "Korach - Shalom Bayit",
        speaker: "R' Yaakov Harari",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v377953",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/377953/377953-syhg71.jpg",
        imageAlt: "R' Yaakov Harari presenting Korach - Shalom Bayit",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9377953"
    },
    {
        id: "naso-shalom-bayit-strategy",
        type: "video",
        title: "Naso: Shalom Bayit Strategy",
        speaker: "R' Shlomo Farhi",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v193820",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/193820/193820.jpg",
        imageAlt: "R' Shlomo Farhi presenting Naso: Shalom Bayit Strategy",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9193820"
    },
    {
        id: "parenting-shalom-bayit-panel",
        type: "video",
        title: "Parenting & Shalom Bayit Panel",
        speaker: "Chazaq Event",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v56619",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/56619/56619.jpg",
        imageAlt: "Speakers at the Parenting and Shalom Bayit Panel",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "956619"
    },
    {
        id: "shalom-bayit-ultimate-pursuit",
        type: "video",
        title: "Shalom Bayit - The Ultimate Pursuit",
        speaker: "R' Paysach Krohn",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v21134",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/21134/21134-sqiltn.jpg",
        imageAlt: "R' Paysach Krohn presenting Shalom Bayit - The Ultimate Pursuit",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "921134"
    },
    {
        id: "must-know-for-marriage",
        type: "video",
        title: "Must Know for Marriage",
        speaker: "R' Joey Haber",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v305084",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/305084/305084.jpg",
        imageAlt: "R' Joey Haber presenting Must Know for Marriage",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9305084"
    },
    {
        id: "marriages-sink-titanic",
        type: "video",
        title: "Why Some Marriages Sink Like the Titanic — And How Yours Can Stay Afloat!",
        speaker: "R' Akiva Haimowitz",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v337277",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/337277/337277.jpg",
        imageAlt: "R' Akiva Haimowitz presenting Why Some Marriages Sink Like the Titanic",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9337277"
    },
    {
        id: "marriages-rowing-upstream",
        type: "video",
        title: "Why Some Marriages Feel Like Rowing Upstream — How to Sail Smoothly Instead!",
        speaker: "R' Akiva Haimowitz",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v338846",
        imageUrl: "https://ta-lectures.s3.us-east-005.backblazeb2.com/thumbnails/338846/338846.jpg",
        imageAlt: "R' Akiva Haimowitz presenting Why Some Marriages Feel Like Rowing Upstream",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9338846"
    },
    {
        id: "speech-about-marriage-emet",
        type: "video",
        source: "youtube",
        title: "Speech about Marriage at \"Emet\"",
        speaker: "Rabbi YY Jacobson",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=xif_pqs2DPs",
        embedUrl: "https://www.youtube-nocookie.com/embed/xif_pqs2DPs?rel=0",
        imageAlt: "Speech about Marriage at Emet by Rabbi YY Jacobson",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "kabbalistic-difference-men-women",
        type: "video",
        source: "youtube",
        title: "A Kabbalistic Difference Between Men and Women",
        speaker: "R. YY Jacobson · TorahAnytime",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=oLxvUVTEAT4",
        embedUrl: "https://www.youtube-nocookie.com/embed/oLxvUVTEAT4?rel=0",
        imageAlt: "A Kabbalistic Difference Between Men and Women by R. YY Jacobson",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_xYJON0S7WWo",
        type: "video",
        source: "youtube",
        title: "Shalom Bayit Reality Check",
        speaker: "R' Benzion Klatzko · TorahAnytime",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=xYJON0S7WWo",
        embedUrl: "https://www.youtube-nocookie.com/embed/xYJON0S7WWo?rel=0",
        imageUrl: "https://i.ytimg.com/vi/xYJON0S7WWo/hqdefault.jpg",
        imageAlt: "Shalom Bayit Reality Check by R' Benzion Klatzko",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_9SHfeLJqTGk",
        type: "video",
        source: "youtube",
        title: "What Is Shalom Bayis?",
        speaker: "Miriam Zeitlin",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=9SHfeLJqTGk",
        embedUrl: "https://www.youtube-nocookie.com/embed/9SHfeLJqTGk?rel=0",
        imageUrl: "https://i.ytimg.com/vi/9SHfeLJqTGk/hqdefault.jpg",
        imageAlt: "What Is Shalom Bayis by Miriam Zeitlin",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_charqMMqfhE",
        type: "video",
        source: "youtube",
        title: "The Marriage Spark",
        speaker: "Miriam Zeitlin",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=charqMMqfhE",
        embedUrl: "https://www.youtube-nocookie.com/embed/charqMMqfhE?rel=0",
        imageUrl: "https://i.ytimg.com/vi/charqMMqfhE/hqdefault.jpg",
        imageAlt: "The Marriage Spark by Miriam Zeitlin",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_Z8m7IZv5LsM",
        type: "video",
        source: "youtube",
        title: "The Magic of Shabbat and Shalom Bayit Without Digital Distractions",
        speaker: "Hidabroot · Torah & Judaism",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=Z8m7IZv5LsM",
        embedUrl: "https://www.youtube-nocookie.com/embed/Z8m7IZv5LsM?rel=0",
        imageUrl: "https://i.ytimg.com/vi/Z8m7IZv5LsM/hqdefault.jpg",
        imageAlt: "The Magic of Shabbat and Shalom Bayit Without Digital Distractions",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_-o3dHk_eOk8",
        type: "video",
        source: "youtube",
        title: "The Phone Is Destroying Shalom Bayit",
        speaker: "Rabbi David Pinto",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=-o3dHk_eOk8",
        embedUrl: "https://www.youtube-nocookie.com/embed/-o3dHk_eOk8?rel=0",
        imageUrl: "https://i.ytimg.com/vi/-o3dHk_eOk8/hqdefault.jpg",
        imageAlt: "The Phone Is Destroying Shalom Bayit by Rabbi David Pinto",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_BYH3KUyCQ-k",
        type: "video",
        source: "youtube",
        title: "The Essence of Shalom Bayis",
        speaker: "Rabbi Shimon Russell",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=BYH3KUyCQ-k",
        embedUrl: "https://www.youtube-nocookie.com/embed/BYH3KUyCQ-k?rel=0",
        imageUrl: "https://i.ytimg.com/vi/BYH3KUyCQ-k/hqdefault.jpg",
        imageAlt: "The Essence of Shalom Bayis by Rabbi Shimon Russell",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_aTOqoXR44Z0",
        type: "video",
        source: "youtube",
        title: "We Will Be Judged on How We Treat Our Wives",
        speaker: "Makor HaChaim",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=aTOqoXR44Z0",
        embedUrl: "https://www.youtube-nocookie.com/embed/aTOqoXR44Z0?rel=0",
        imageUrl: "https://i.ytimg.com/vi/aTOqoXR44Z0/hqdefault.jpg",
        imageAlt: "We Will Be Judged on How We Treat Our Wives from Makor HaChaim",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_94T-boYVG-A",
        type: "video",
        source: "youtube",
        title: "The Secrets of Love: The Best Jewish Advice for Your Powerful Marriage",
        speaker: "Rabbi YY Jacobson",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=94T-boYVG-A",
        embedUrl: "https://www.youtube-nocookie.com/embed/94T-boYVG-A?rel=0",
        imageUrl: "https://i.ytimg.com/vi/94T-boYVG-A/hqdefault.jpg",
        imageAlt: "The Secrets of Love by Rabbi YY Jacobson",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_NYM8brG_buc",
        type: "video",
        source: "youtube",
        title: "Marriage & Trauma",
        speaker: "Rabbi YY Jacobson",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=NYM8brG_buc",
        embedUrl: "https://www.youtube-nocookie.com/embed/NYM8brG_buc?rel=0",
        imageUrl: "https://i.ytimg.com/vi/NYM8brG_buc/hqdefault.jpg",
        imageAlt: "Marriage and Trauma by Rabbi YY Jacobson",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_iKHuSr5_zzc",
        type: "video",
        source: "youtube",
        title: "The Real Reason Relationships Fall Apart — and How to Fix Yours",
        speaker: "Jewish Learning Institute",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=iKHuSr5_zzc",
        embedUrl: "https://www.youtube-nocookie.com/embed/iKHuSr5_zzc?rel=0",
        imageUrl: "https://i.ytimg.com/vi/iKHuSr5_zzc/hqdefault.jpg",
        imageAlt: "The Real Reason Relationships Fall Apart from the Jewish Learning Institute",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "youtube_FVuJb2G2Ca8",
        type: "video",
        source: "youtube",
        title: "10 Dumb Mistakes Smart Couples Make",
        speaker: "Rabbi Bentzion Shafier · Living Lchaim",
        primaryLabel: "Watch on YouTube",
        primaryUrl: "https://www.youtube.com/watch?v=FVuJb2G2Ca8",
        embedUrl: "https://www.youtube-nocookie.com/embed/FVuJb2G2Ca8?rel=0",
        imageUrl: "https://i.ytimg.com/vi/FVuJb2G2Ca8/hqdefault.jpg",
        imageAlt: "10 Dumb Mistakes Smart Couples Make with Rabbi Bentzion Shafier",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "torahanytime_421705",
        type: "video",
        source: "torahanytime",
        title: "Tips for Marriage",
        speaker: "R' Eli Mansour",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v421705",
        imageUrl: "https://www.torahanytime.com/images/audio-thumb-male.svg",
        imageAlt: "TorahAnytime artwork for Tips for Marriage by R' Eli Mansour",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9421705"
    },
    {
        id: "itorah_6436",
        type: "video",
        source: "itorah",
        title: "Marriage and Money",
        speaker: "Rabbi Eli Mansour",
        primaryLabel: "Watch on iTorah",
        primaryUrl: "https://itorah.com/lecture/video/rabbi-eli-mansour/marriage-and-money/6436/1",
        imageUrl: "https://itorah.com/assets/img/social/EliMansour.png",
        imageAlt: "Rabbi Eli Mansour presenting Marriage and Money",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "torahanytime_373785",
        type: "video",
        source: "torahanytime",
        title: "Eshet Chayil 36: The Three Rules of Marriage",
        speaker: "R' Meyer Yedid",
        primaryLabel: "Watch on TorahAnytime",
        primaryUrl: "https://MyTaT.me/v373785",
        imageUrl: "https://www.torahanytime.com/images/audio-thumb-male.svg",
        imageAlt: "TorahAnytime artwork for The Three Rules of Marriage by R' Meyer Yedid",
        dialIn: "(605) 605-2220",
        dialInHref: "tel:+16056052220",
        extension: "9373785"
    },
    {
        id: "book-recommendation",
        type: "book",
        title: "Dear Daughter",
        speaker: "Rabbi Eliyohu Goldschmidt",
        primaryLabel: "Shop on Amazon",
        primaryUrl: "https://a.co/d/0ja740ak",
        imageUrl: "https://s3.us-east-2.amazonaws.com/cdn.platform.capitalc.co/media/7159/conversions/dear-daughter-1-lightbox.jpg",
        imageAlt: "Cover of Dear Daughter by Rabbi Eliyohu Goldschmidt",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "dear-son",
        type: "book",
        title: "Dear Son",
        speaker: "Rabbi Eliyohu Goldschmidt",
        primaryLabel: "Shop on Amazon",
        primaryUrl: "https://a.co/d/067oAlwe",
        imageUrl: "https://cdn.powered-by-nitrosell.com/product_images/11/2547/large-DEAR%20SON%20HC.jpg",
        imageAlt: "Cover of Dear Son by Rabbi Eliyohu Goldschmidt",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "smart-couples-mistakes",
        type: "book",
        title: "The 10 Really Dumb Mistakes That Very Smart Couples Make",
        speaker: "Rabbi Ben Tzion Shafier",
        primaryLabel: "Shop on Amazon",
        primaryUrl: "https://a.co/d/0bm9pHUJ",
        imageUrl: "https://images-na.ssl-images-amazon.com/images/P/1680251767.01.L.jpg",
        imageAlt: "Cover of The 10 Really Dumb Mistakes That Very Smart Couples Make by Rabbi Ben Tzion Shafier",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "first-year-of-marriage",
        type: "book",
        title: "The First Year of Marriage",
        speaker: "Rabbi Abraham J. Twerski",
        primaryLabel: "Shop on Amazon",
        primaryUrl: "https://a.co/d/06KHWd84",
        imageUrl: "https://covers.openlibrary.org/b/isbn/9781578194322-L.jpg",
        imageAlt: "Cover of The First Year of Marriage by Rabbi Abraham J. Twerski",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "secrets-of-the-soul-volume-two",
        type: "book",
        title: "Secrets of the Soul — Volume 2",
        speaker: "Rav Shlomo Hoffman",
        primaryLabel: "Shop on Amazon",
        primaryUrl: "https://a.co/d/0ib3kC2P",
        imageUrl: "https://images-na.ssl-images-amazon.com/images/P/168025684X.01.L.jpg",
        imageAlt: "Cover of Secrets of the Soul Volume 2 by Rav Shlomo Hoffman",
        dialIn: "",
        dialInHref: "",
        extension: ""
    },
    {
        id: "relationship-to-return-to",
        type: "inspiration",
        title: "A Relationship to Return To",
        speaker: "Connected Parenting · Kent Hoffman",
        imageUrl: "/inspiration-security-relationship.png?v=2026-08-07.2",
        imageAlt: "A father holding his child beside a quote about security being the presence of a relationship to return to"
    }
];
